# Generated by Django 3.0.4 on 2020-03-28 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('list_summary', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Lists',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='Tasklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_content', models.TextField()),
                ('task_due', models.DateTimeField(default=datetime.datetime(2020, 3, 28, 21, 10, 39, 865004), verbose_name='date task is due')),
                ('task_list', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.List', verbose_name='List')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='list_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Owner', verbose_name='Owner'),
        ),
    ]
