# Generated by Django 3.0.4 on 2020-04-02 10:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20200402_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='task_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_due',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 16, 21, 45, 318539), verbose_name='date task is due'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_list',
            field=models.TextField(),
        ),
    ]
