# Generated by Django 3.0.4 on 2020-04-02 11:05

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200402_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Lists',
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_due',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 16, 35, 53, 233362), verbose_name='date task is due'),
        ),
    ]
