# Generated by Django 3.0.4 on 2020-04-17 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200402_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='task_content',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='task_priority',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='task_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_due',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 23, 21, 26, 241226), verbose_name='date task is due'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Lists'),
        ),
    ]
